version: '2' # specify docker-compose version
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    book-app:
        build: book-app
        ports:
            - "4200:4200"
    backend:
        build: book-backend
        ports:
            - 3000:3000
        
   