version: '2' # specify docker-compose version
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
    book-app:
        build: book-app
        ports:
            - "4200:4200"
        volumes:
            - ./book-app:/app 
    backend:
        build: backend
        volumes:
            - ./backend/backend:/
        ports:
            - 3000:3000
        
   